#!/bin/sh
set -e

case "$1" in
    configure)
        chmod 755 /usr/share/kdg-kiosk/kiosk-config.sh || true
        chmod 755 /usr/share/kdg-kiosk/startup-script.sh || true
    ;;
esac

CONFIG_TEMPLATE="/etc/squid/conf.d/squid.conf.template"
CONFIG_FILE="/etc/squid/squid.conf"

echo ">> [kdg-kiosk] Generating initial Squid configuration..."

if [ -f "$CONFIG_TEMPLATE" ]; then
    export PROXY_IP="127.0.0.1"
    export PROXY_PORT="3128"
    export BLOCKED_PAGE_URL="http://127.0.0.1/blocked.html"
    export DENIED_PAGE_URL="http://127.0.0.1/denied.html"

    envsubst < "$CONFIG_TEMPLATE" > "$CONFIG_FILE"

    echo ">> [kdg-kiosk] Enabling and Restarting Squid service..."
    deb-systemd-invoke enable squid.service || true
    deb-systemd-invoke restart squid.service || true
else
    echo ">> [kdg-kiosk] Warning: squid.conf.template not found at $CONFIG_TEMPLATE"
fi

echo ">> [kdg-kiosk] Squid configured successfully."



exit 0