#!/bin/sh
set -e

case "$1" in
    configure)
        chmod 755 /usr/share/kdg-kiosk/kiosk-config.sh || true
        chmod 755 /usr/share/kdg-kiosk/startup-script.sh || true
    ;;
esac

exit 0

#DEBHELPER#

